#!/bin/bash -eu

local num_files_moved="$1"

function log () {
  echo "$( date )" >> "$LOG_FILE"
  echo "$1" >> "$LOG_FILE"
}

if [ -r "/root/.teslaCamPushoverCredentials" ] && [ $num_files_moved > 0]
then
  log "Sending Pushover message for moved files."

  source /root/.teslaCamPushoverCredentials

  curl -F "token=$pushover_app_key" \
  -F "user=$pushover_user_key" \
  -F "title=Dashcam Copy Complete" \
  -F "message=$num_files_moved file(s) were copied." \
  https://api.pushover.net/1/messages
fi
