#!/bin/bash -eu

if [ "$(whoami)" != "root" ]
then
  echo "STOP: Run sudo -i."
  exit 1
fi

function check_variable () {
  local var_name="$1"
  if [ -z "${!var_name+x}" ]
  then
    echo "STOP: Define the variable $var_name like this: export $var_name=value"
    exit 1
  fi
}

check_variable "archiveserver"
check_variable "sharename"
check_variable "shareuser"
check_variable "sharepassword"
check_variable "campercent"

serverunreachable=false
ping -c 1 -w 1 "$archiveserver" 1>/dev/null 2>&1 || serverunreachable=true

if [ "$serverunreachable" = true ]
then
  echo "STOP: The archive server $archiveserver is unreachable. Try specifying its IP address instead."
  exit 1
fi

archiveserverip="$(getent hosts $archiveserver | cut -d' ' -f1)"

available_space="$(($(df --output=avail / | tail -1) - 1000000))"

if [ "$available_space" -lt 0 ]
then
  echo "STOP: The MicroSD card is too small."
  exit 1
fi

function add_drive () {
  local name="$1"
  local label="$2"
  local size="$3"

  local filename="$4"
  fallocate -l "$size"K "$filename"
  mkfs.vfat "$filename" -F 32 -n "$label"

  local mountpoint=/mnt/"$name"

  mkdir "$mountpoint"
  echo "$filename $mountpoint vfat noauto,users,umask=000 0 0" >> /etc/fstab
}

pushd ~

cp /boot/cmdline.txt ~
cat ~/cmdline.txt | sed 's/[[:space:]]\+modules-load=[^ [:space:]]\+//' | sed 's/rootwait/rootwait modules-load=dwc2/' > /boot/cmdline.txt
rm ~/cmdline.txt

mkdir /mnt/archive

echo "" >> /etc/fstab
echo "//$archiveserverip/$sharename /mnt/archive cifs vers=3,credentials=/root/.teslaCamArchiveCredentials,iocharset=utf8,file_mode=0777,dir_mode=0777 0" >> /etc/fstab

echo "username=$shareuser" > /root/.teslaCamArchiveCredentials
echo "password=$sharepassword" >> /root/.teslaCamArchiveCredentials

mkdir /root/bin

wget https://raw.githubusercontent.com/cimryan/teslausb/u/cimryan/music/windows_archive/archiveloop
sed s/ARCHIVE_HOST_NAME=archiveserver/ARCHIVE_HOST_NAME=$archiveserver/ ~/archiveloop > /root/bin/archiveloop
rm ~/archiveloop
chmod +x /root/bin/archiveloop

pushd /root/bin
wget https://raw.githubusercontent.com/cimryan/teslausb/u/cimryan/music/windows_archive/archive-teslacam-clips
chmod +x archive-teslacam-clips
popd

echo "#!/bin/bash -eu" > ~/rc.local
tail -n +2 /etc/rc.local | sed '$d' >> ~/rc.local
cat << 'EOF' >> ~/rc.local
LOGFILE=/tmp/rc.local.log

function log () {
  echo "$( date )" >> "$LOGFILE"
  echo "$1" >> "$LOGFILE"
}

log "Launching archival script..."
/root/bin/archiveloop &
log "All done"
exit 0
EOF

cat ~/rc.local > /etc/rc.local
rm ~/rc.local

cam_disk_size="$(( $available_space * $campercent / 100 ))"
cam_disk_file_name="/cam_disk.bin"
add_drive "cam" "CAM" "$cam_disk_size" "$cam_disk_file_name"

if [ "$campercent" -lt 100 ]
then
  musicpercent="$(( 100 - $campercent ))"
  music_disk_size="$(( $available_space * $musicpercent / 100 ))"
  music_disk_file_name="/music_disk.bin"
  add_drive "music" "MUSIC" "$music_disk_size" "$music_disk_file_name"
  echo "options g_mass_storage file=$cam_disk_file_name,$music_disk_file_name removable=1,1 ro=0,0 stall=0 iSerialNumber=123456" > /etc/modprobe.d/g_mass_storage.conf
else
  echo "options g_mass_storage file=$cam_disk_file_name removable=1 ro=0 stall=0 iSerialNumber=123456" > /etc/modprobe.d/g_mass_storage.conf
fi

cp /etc/hosts ~
sed s/raspberrypi/teslausb/g ~/hosts > /etc/hosts

cp /etc/hostname ~
sed s/raspberrypi/teslausb/g ~/hostname > /etc/hostname