#!/bin/bash

i=$1
flash_count=0
flash_count=$((i + 1 )) 

function led_off () {
echo 1 | sudo tee /sys/class/leds/led0/brightness > /dev/null
}

function led_on () {
echo 0 | sudo tee /sys/class/leds/led0/brightness > /dev/null
}

function led_flash () {
   led_on
   sleep .2
   led_off
}

function flash () {
  local COUNTER=0
  sleep 2
  while [ ${COUNTER} -lt ${flash_count} ]
  do  
    led_flash
    let COUNTER=COUNTER+1
  done
}

flash
sleep 5

exit 0
